config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses
  end

  resources :doses, only: [:destroy, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    @doses = Dose.where(cocktail_id: @cocktail.id)
  end

  def new
    @cocktail = Cocktail.new
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    # we need `restaurant_id` to associate review with corresponding restaurant
    @dose = Dose.new(doses_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def doses_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<div class="container">
  <h1>Add a new cocktail</h1>
  <%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>
</div>

app/views/cocktails/index.html.erb
    <div class="col-12">
      <h1>Cocktails</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
        <p>All <%=@cocktails.count%> Cocktails</p>
    </div>

  </div>
  <div class="row">
    <% @cocktails.each do |cocktail|  %>
      <div class="col-4">
        <div class="flat-card">
          <% if cocktail.photo.attached? %>
        <%= cl_image_tag cocktail.photo.key, height: 200, width: 350, crop: :fill, class: 'flat-card-image' %>
        <% else %>
        <%= image_tag "https://source.unsplash.com/collection/8462744/1600x900", height: 200, width: 350, crop: :fill, alt: "alttext" %>
        <% end %>
          <!-- <div class="flat-card-image" style="background-image: url('https://source.unsplash.com/collection/8462744/1600x900')"></div> -->
          <div class="flat-card-content">
            <div class="flat-card-title">
              <h4><%= cocktail.name %></h4>
            </div>
            <p><%=  %></p>
            <div class="flex">
              <div class="flex">
                <i class="material-icons mr-2"></i><span><%=  %></span>
              </div>
              <div class="flex ml-3">
                <i class="material-icons mr-2"></i> <%=%>
              </div>
            </div>
          </div>
          <div class="flat-card-actions">
            <%= link_to "More info", cocktail_path(cocktail) %>
            <%= link_to "Edit", edit_cocktail_path(cocktail), class: "ml-3 text-warning" %>
            <%= link_to 'Delete', cocktail_path(cocktail),
            data: {:confirm => 'Are you sure?'}, :method => :delete, class: "ml-3 text-danger" %>
          </div>
        </div>
      </div>
    <% end %>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>Add a new cocktail</h1>
  <%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>
</div>

app/views/cocktails/show.html.erb
<div class="banner mt-2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @cocktail.photo.key%>')"><%= @cocktail.name %></div>
  <br>
  <br>
  <div class="container margin-top-negative">
    <div class="row">
      <div class="col-7 mt-3">
        <div class="flat-show-card">
          <h1><%= @cocktail.name %></h1>
          <br>
          <h3>Doses & Ingredients</h3>
          <% @cocktail.doses.each do |cocktail| %>
          <p class="flat-show-address"><%=cocktail.ingredient.name%> | <%= cocktail.description  %> | <%= link_to 'delete', dose_path(cocktail.id), data: {:confirm => 'Are you sure?'}, :method => :delete %>
           <% end %>
           </p>
          <% if @cocktail.photo.attached? %>
        <%= cl_image_tag @cocktail.photo.key, height: 200, width: 300, crop: :fill %>
        <% else %>
        <%= image_tag "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200", height: 200, width: 300, alt: "alttext" %>
        <% end %>
        </div>
        <div class="flat-show-card">
          <div class="map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=5 Queensmill Road London SW6 6JP&zoom=13&scale=2&size=1000x1000&maptype=roadmap&markers=color:red%7C5 Queensmill Road London SW6 6JP&key=AIzaSyBtaHK-BLhBg7TruJu8iKk_wETqZMJM-GY')"></div>
        </div>
      </div>
      <br>
      <div class="col-5 mt-5">
        <div class="flat-show-card">
          <h5>Add a new dose!</h5>
          <%= simple_form_for [@cocktail, @dose] do |f| %>
          <%= f.input :description %>
          <%= f.association :ingredient %>
          <%= f.submit class: "btn btn-success"%>
          <% end %>
        </div>
        <div class="flat-show-card">
          <div class="flex">
            <div class="flex">
              <i class="material-icons mr-2"></i><span><%=%></span>
            </div>
            <div class="flex ml-3">
              <i class="material-icons mr-2"></i> <%=%>
            </div>
          </div>
        </div>
        <div class="flat-show-card">

          </div>
        </div>
        <div class="container">


        <br>

          <%= link_to "Back to Cocktails list", cocktails_path, class: 'btn btn-success' %>

        </div>
      </div>


    </div>
    <br>
    <br>
</div>

app/views/doses/new.html.erb
new.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Mister Cocktail</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto flex">
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          <!-- <a class="btn btn-outline-primary my-2 my-sm-0 ml-2" href="/flats/new">Add Flat</a> -->
          <%= link_to "Add Cocktail", new_cocktail_path, class: 'btn btn-outline-primary my-2 my-sm-0 ml-2' %>
        </div>
      </div>
    </nav>
    <div class="container mt-3">
      <div class="row">
        <%= yield %>
        <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
        <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      </div>
    </div>
  </body>
</html>